language: node_js
dist: trusty
node_js:
- '4'
- '6'
- '8'
- '10'
env:
- NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly
script:
- npm run coverage
notifications:
  email:
    - nodejs-build-notifications+travis@googlegroups.com
